# disable = true;   module is deactivated
# disable = false;  module is enabled


# Don't print a new line at the start of the prompt
add_newline = false
[line_break]
disabled = true

[character]
# success_symbol = "[âœ](bold green)"
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"

[cmd_duration]
disabled = true

[directory]
truncation_symbol = "â€¦/"
truncate_to_repo = true
style = "bold cyan"
read_only = " ğŸ”’"
home_symbol = "~"

[git_branch]
symbol = "î‚  "
style = "bold purple"
always_show_remote = false
disabled = false

[git_state]
style = "bold yellow"
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[îŠ› PICKING](${style})"
merge = "[îœ§ MERGING](${style})"
rebase = "[î¿ REBASING](${style})"
revert = "[ï† REVERTING](${style})"
bisect = "[ï„„ BISECTING](${style})"
am_or_rebase = "[ï¨¶AM/REBASE](${style})"
am = "[ï«…AM](${style})"
disabled = false

[git_status]
conflicted = "="
ahead = "â‡¡"
behind = "â‡£"
diverged = "â‡•"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"
style = "bold red"
disabled = false

[hostname]
disabled = true

[java]
symbol = "îœ¸ "
style = "red dimmed"
format = "$symbol[${version} ](${style})"
disabled = false

[kotlin]
symbol = "ğŸ…º "
style = "bold blue"
kotlin_binary = "kotlinc"
format = "$symbol[${version} ](${style})"
disabled = false

[lua]
format = "$symbol[${version} ](${style})"
symbol = "î˜  "
style = "bold blue"
lua_binary = "lua"
disbled = false

